### ISSUE TITLE
AttributeError: 'module' object has no attribute 'get_book_dict'

### ISSUE THREAD

**Issue by arpit1997** [pyexcel/pyexcel#87] opened 2017-06-20 17:53 UTC
I followed the [docs](https://pyexcel.readthedocs.io/en/latest/tutorial_data_conversion.html#how-to-obtain-a-dictionary-from-a-multiple-sheet-book) and tried to run the code below:
`>>> import pyexcel`
`>>> from pyexcel._compact import OrderedDict`
`>>> my_dict = pyexcel.get_book_dict(file_name="example_series.xls", name_columns_by_row=0)`
`>>> isinstance(my_dict, OrderedDict)`

But it raise the error. But when i try
`from pyexcel.core import *` function `get_book_dict` works. Any help why this issue is coming. If docs are not updated then update it or assign me the issue i will do it.

**Comment by chfw** [comment] 2017-06-20 19:05
Here's what I am trying to produce:

    Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25)
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pyexcel
    >>> from pyexcel._compact import OrderedDict
    >>> my_dict = pyexcel.get_dict(file_name='example.xlsx', name_columns_by_row=0)
    >>> isinstance(my_dict, OrderedDict)
    True
    >>>

By the way, all examples in the doc were tested.

**Comment by arpit1997** [comment] 2017-06-20 19:11
sorry i wrote `get_dict` by mistake. I updated the comment please try to reproduce it. and version i used is pyexcel 0.5.0

**Comment by chfw** [comment] 2017-06-20 19:36
Cannot reproduce it either::

    >>> my_dict = pyexcel.get_dict(file_name='example.xlsx', name_columns_by_row=0)
    >>> isinstance(my_dict, OrderedDict)
    True
    >>> my_dict = pyexcel.get_book_dict(file_name='example.xlsx', name_columns_by_row=0)
    >>> isinstance(my_dict, OrderedDict)
    True
    >>>

**Comment by arpit1997** [comment] 2017-06-20 19:51
![screenshot from 2017-06-21 01 17 38](https://user-images.githubusercontent.com/10682054/27352921-fa39c6e2-561f-11e7-86b3-d45d9e363e84.png)

**Comment by chfw** [comment] 2017-06-20 20:00
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pyexcel as p
    >>> p.get_book_dict()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/jaska/github/pyexcel/pyexcel/core.py", line 207, in get_book_dict
        book = get_book(**keywords)
      File "/Users/jaska/github/pyexcel/pyexcel/core.py", line 46, in get_book
        book_stream = sources.get_book_stream(**keywords)
      File "/Users/jaska/github/pyexcel/pyexcel/internal/core.py", line 32, in get_book_stream
        a_source = SOURCE.get_book_source(**keywords)
      File "/Users/jaska/github/pyexcel/pyexcel/internal/source_plugin.py", line 83, in get_book_source
        **keywords)
      File "/Users/jaska/github/pyexcel/pyexcel/internal/source_plugin.py", line 65, in get_a_plugin
        library=source_library, **keywords)
      File "/Users/jaska/github/pyexcel/pyexcel/internal/source_plugin.py", line 48, in load_me_now
        _error_handler(action, **keywords)
      File "/Users/jaska/github/pyexcel/pyexcel/internal/source_plugin.py", line 140, in _error_handler
        raise exceptions.UnknownParameters("No parameters found!")
    pyexcel.exceptions.UnknownParameters: No parameters found!

Above should what is expected. Could I get a list pyexcel library from your environment?

This must be related to the latest release of pyexcel 0.5.0 and pyexcel-io 0.4.0 and its plugins.

**Comment by arpit1997** [comment] 2017-06-20 20:05
> pyexcel 0.5.0 and pyexcel-io 0.4.0 and its plugins
I have both these. Check the below file. Its a pip freeze from my system

[lists.txt](https://github.com/pyexcel/pyexcel/files/1089540/lists.txt)

**Comment by chfw** [comment] 2017-06-20 23:30
I have tried 2.7.13 on OSX and Fedora 25 and could not reproduce it. Could I suggest trying to reinstall pyexcel and pyexcel-io? pip uninstall pyexcel and pyexcel-io until both packages were not in your environment and then pip install pyexcel. Just in case that the older versions pyexcel or pyexcel-io has a role in confusing Python import.

**Comment by chfw** [comment] 2017-06-20 23:42
Another thing I could think of is to [trace the pyexcel startup](http://pyexcel.readthedocs.io/en/latest/logging.html). Since 0.5.0, the plugin interface has been refactored into an independent library call lml, which could be a potential cause.

    import logging
    import logging.config
    logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        level=logging.DEBUG)

    import pyexcel
    pyexcel.get_book_dict()

Here is the command to run it:

    python trace-pyexcel.py > trace_log.txt 2>&1

And here is ok-log:


[trace_log.txt](https://github.com/pyexcel/pyexcel/files/1089938/trace_log.txt)

**Comment by chfw** [comment] 2017-06-21 07:30
https://github.com/pyexcel/pyexcel-io/issues/37 shows the same symptom but it was pyexcel-io 0.3.4 caused it.

**Comment by chfw** [comment] 2017-06-21 07:51
Here is a relevant report before pyexcel 0.5.0. It is fixed by re-installing pyexcel. https://stackoverflow.com/questions/44103036/python-error-attributeerror-module-pyexcel-has-no-attribute-get-sheet

**Comment by chfw** [comment] 2017-07-05 11:47
This issue was transferred to #90.

**Closed by chfw** 2017-07-05 11:47 UTC

**Comment by chfw** [comment] 2017-07-05 14:37
please try pyexcel-io v0.4.2. I think it should fix the problem.
