### ISSUE TITLE
Chinese character not supported.

### ISSUE THREAD

**Issue by TankyH** [pyexcel/pyexcel#60] opened 2016-09-28 03:14 UTC
In [18]: array = [['这', '是', '中', '文'], ['这', '是', '中', '文']]

In [19]: pyexcel.Sheet(array)

Out[19]: ---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
...
UnicodeEncodeError: 'ascii' codec can't encode characters in position 58-61: ordinal not in range(128)

**Comment by chfw** [comment] 2016-09-28 16:41
Reproduced in python 2. The root cause is the sys.getdefaultencoding() equals "ascii", which obviously could not encode Chinese texts.  However, the fix is not extended to python-texttable which produces distorted output(Chinese characters should have been counted to occupy two spaces of an alphabet). Therefore, the fix only removes the UnicodeEncodeError in python 2.

Please verify using the master branch:

    pip install https://github.com/pyexcel/pyexcel/archive/master.zip

**Comment by chfw** [comment] 2016-10-28 22:00
released in v0.3.0

**Closed by chfw** 2016-10-28 22:00 UTC
Labels: bug
